cartapp/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove

app_name = "cartapp"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<url>", cart_add, name="cart_add"),
    path("remove/<url>", cart_remove, name="cart_remove"),
]

mainapp/urls.py
from django.urls import path
from .views import MainView, contact, about

urlpatterns = [
    path("", MainView.as_view(), name="main"),
    path("contacts/", contact, name="contacts"),
    path("about/", about, name="about"),
]

onlineshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainapp.urls")),
    path("", include("detailsapp.urls")),
    path("", include("filterprodapp.urls")),
    path("", include("sendemail.urls")),
    path("cart/", include("cartapp.urls", namespace="cart")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordersapp/urls.py
from django.urls import path
from .views import order_create

app_name = "ordersapp"

urlpatterns = [
    path("create/", order_create, name="order_create"),
]

mainapp/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Categories(models.Model):
    name = models.CharField(
        "Название категории",
        max_length=25,
        db_index=True,
    )
    image = models.ImageField("Изображение", upload_to="image/catigories/%Y/%m/%d")
    url = models.SlugField(
        max_length=52,
        db_index=True,
        blank=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def save(
        self,
        *args,
    ):
        if not self.id:
            self.url = slugify(self.name)
        super(Categories, self).save(*args)

    def get_absolute_url(self):
        return reverse("scat", kwargs={"cat_slug": self.url})

    def __str__(self):
        return f"{self.name}"


class Brands(models.Model):
    name = models.CharField("Бренд", max_length=40, db_index=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Products(models.Model):
    name_model = models.CharField("Название", max_length=100, db_index=True)
    discription = models.TextField("Описание", max_length=1000, db_index=True)
    price = models.IntegerField(
        "Цена",
    )
    size_discount = models.IntegerField("Скидка", default=0)
    main_image = models.ImageField(
        "Главное изображение",
        upload_to="image/products/%Y/%m/%d",
    )
    category = models.ForeignKey(
        Categories,
        on_delete=models.CASCADE,
    )
    brand = models.ForeignKey(
        Brands,
        on_delete=models.CASCADE,
    )
    discount = models.BooleanField(default=False)
    available = models.BooleanField(default=True)
    url = models.SlugField(max_length=52, db_index=True, blank=True)

    class Meta:
        ordering = ["category"]
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def price_with_disk(self):
        return self.price - round(self.price * (self.size_discount / 100))

    def save(
        self,
        *args,
    ):
        if not self.id:
            self.url = slugify(self.name_model)
        super(Products, self).save(*args)

    def __str__(self):
        return f"{self.name_model}"


class Image(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    image = models.ImageField("Изображение", upload_to=f"image/products/%Y/%m/%d")

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"

    def __str__(self):
        return f"{self.product}"

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View

from cartapp.cart import Cart
from cartapp.forms import CartAddProductForm
from .models import Categories, Products


class MainView(View):
    def get(self, request, *args, **kwargs):
        prod = Products.objects.order_by("?")[:6]
        categories = Categories.objects.order_by("?")[:3]
        context = {
            "prods": prod,
            "cat": categories,
        }
        return render(request, "mainapp/main.html", context=context)


def cart_detail(request):
    cart = Cart(request)
    cart_form = CartAddProductForm()
    return render(
        request,
        "mainapp/blocks/header.html",
        {"cart": cart, "cart_product_form": cart_form},
    )


def contact(request):
    return render(request, "mainapp/plug.html", context={})


def about(request):
    return render(request, "mainapp/plug.html", context={})

mainapp/templates/mainapp/blocks/application.html
<div id="newsletter" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <div class="newsletter">
                    <p>Подпишитесь на <strong>НОВЫЕ ПРЕДЛОЖЕНИЯ</strong></p>
                    <div>
                        <h5><a href="{% url 'contact' %}" class="primary-btn"><i class="fa fa-envelope"></i> Оставить
                        заявку</a></h5>
                    </div>
                    <ul class="newsletter-follow">
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>

mainapp/templates/mainapp/blocks/footer.html
<footer id="footer" {% if request.path == '/success/' %} style="background: #15161D;
    position: absolute;
    color: #B9BABC;
    width: 100%;
    bottom: 0;"{% endif %}>
    <!-- top footer -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">О нас</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
                            ut.</p>
                        <ul class="footer-links">
                            <li><a href="#"><i class="fa fa-map-marker"></i> г. Москва, Красная площадь 3</a></li>
                            <li><a href="#"><i class="fa fa-phone"></i> +8-953-511-84-43</a></li>
                            <li><a href="#"><i class="fa fa-envelope-o"></i>technoelec@gmail.com</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">Товары</h3>
                        <ul class="footer-links">
                            <li><a href="#">Ноутбуки</a></li>
                            <li><a href="#">Смартфоны</a></li>
                            <li><a href="#">Камеры</a></li>
                            <li><a href="#">Аксессуары</a></li>
                        </ul>
                    </div>
                </div>

                <div class="clearfix visible-xs"></div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">Информация</h3>
                        <ul class="footer-links">
                            <li><a href="#">О нас</a></li>
                            <li><a href="#">Контакты</a></li>
                            <li><a href="#">Политика конфиденциальности</a></li>
                            <li><a href="#">Заказы</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">Сервис</h3>
                        <ul class="footer-links">
                            <li><a href="">Корзина</a></li>
                            <li><a href="">Заказы</a></li>
                            <li><a href="">Отследить заказ</a></li>
                            <li><a href="">Помощь</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /top footer -->

    <!-- bottom footer -->
    <div id="bottom-footer" class="section">
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12 text-center">
                    <ul class="footer-payments">
                        <li><a href=""><i class="fa fa-cc-visa"></i></a></li>
                        <li><a href=""><i class="fa fa-credit-card"></i></a></li>
                        <li><a href=""><i class="fa fa-cc-paypal"></i></a></li>
                        <li><a href=""><i class="fa fa-cc-mastercard"></i></a></li>
                        <li><a href=""><i class="fa fa-cc-discover"></i></a></li>
                        <li><a href=""><i class="fa fa-cc-amex"></i></a></li>
                    </ul>
                    <span class="copyright">
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i
                            class="fa fa-heart-o" aria-hidden="true"></i> by <a href="">Bob</a>
							</span>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /bottom footer -->
</footer>

mainapp/templates/mainapp/blocks/header.html
<!-- HEADER -->
<header>
    <!-- TOP HEADER -->
    <div id="top-header">
        <div class="container">
            <ul class="header-links pull-left">
                <li><a href=""><i class="fa fa-phone"></i> +8-953-511-84-43</a></li>
                <li><a href=""><i class="fa fa-envelope-o"></i> technoelec@gmail.com</a></li>
                <li><a href=""><i class="fa fa-map-marker"></i> г. Москва, Красная площадь 3</a></li>
            </ul>
            <ul class="header-links pull-right">
                <li><a href=""><i class="fa fa-user-o"></i> Войти</a></li>
            </ul>
        </div>
    </div>
    <!-- /TOP HEADER -->

    <!-- MAIN HEADER -->
    <div id="header">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- LOGO -->
                <div class="col-md-3">
                    <div class="header-logo">
                        <a href="{% url 'main' %}" class="logo">
                            <img src="/static/mainapp/img/logo.png" alt="">
                        </a>
                    </div>
                </div>
                <!-- /LOGO -->

                <!-- SEARCH BAR -->
                <div class="col-md-6">
                    <div class="header-search">
                        <form>
                            <input class="input" placeholder="Введите название">
                            <button class="search-btn">Найти</button>
                        </form>
                    </div>
                </div>
                <!-- /SEARCH BAR -->

                <!-- ACCOUNT -->
                <div class="col-md-3 clearfix">
                    <div class="header-ctn">
                        <!-- Wishlist -->
                        <!-- /Wishlist -->

                        <!-- Cart -->
                        <div class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-shopping-cart"></i>
                                <span>Корзина</span>
                                <div class="qty">{{ cart|length }}</div>
                            </a>
                            <div class="cart-dropdown">
                                <div class="cart-list">
                                    {% for item in cart %}
                                        {% with product=item.product %}
                                            <div class="product-widget">
                                                <div class="product-img">
                                                    <img src="/media/{{ product.main_image }}" alt="">
                                                </div>
                                                <div class="product-body">
                                                    <h3 class="product-name"><a
                                                            href="#">{{ product.brand }} {{ product.name_model }}</a>
                                                    </h3>
                                                    <h4 class="product-price"><span
                                                            class="qty">{{ item.quantity }}x</span>{{ item.total_price }}Р.
                                                    </h4>
                                                </div>
                                            </div>
                                        {% endwith %}
                                    {% endfor %}
                                </div>
                                <div class="cart-summary">
                                    <small>Выбрано товаров {{ cart.get_total_len }}</small>
                                    <h5>ИТОГО: {{ cart.get_total_price }}Р.</h5>
                                </div>
                                <div class="cart-btns">
                                    <a href="{% url 'cart:cart_detail' %}">В корзину</a>
                                    <a href="{% url 'orders:order_create' %}">Оформить <i class="fa fa-arrow-circle-right"></i></a>
                                </div>
                            </div>
                        </div>
                        <!-- /Cart -->

                        <!-- Menu Toogle -->
                        <div class="menu-toggle">
                            <a href="#">
                                <i class="fa fa-bars"></i>
                                <span>Menu</span>
                            </a>
                        </div>
                        <!-- /Menu Toogle -->
                    </div>
                </div>
                <!-- /ACCOUNT -->
            </div>
            <!-- row -->
        </div>
        <!-- container -->
    </div>
    <!-- /MAIN HEADER -->
</header>
<!-- /HEADER -->

<!-- NAVIGATION -->
<nav id="navigation">
    <!-- container -->
    <div class="container">
        <!-- responsive-nav -->
        <div id="responsive-nav">
            <!-- NAV -->
            <ul class="main-nav nav navbar-nav">
                <li class="{% if request.path == '/' %}active{% endif %}"><a href="{% url 'main' %}">Главная</a></li>
                <li class="{% if request.path == '/products/' %}active{% endif %}"><a href="{% url 'filter_prod' %}">Товары</a>
                </li>
                <li class="{% if request.path == '/contact/' %}active{% endif %}"><a href="{% url 'contacts' %}">Контакты</a></li>
                <li class="{% if request.path == '/about/' %}active{% endif %}"><a href="{% url 'about' %}">О нас</a></li>
            </ul>
            <!-- /NAV -->
        </div>
        <!-- /responsive-nav -->
    </div>
    <!-- /container -->
</nav>
<!-- /NAVIGATION -->

mainapp/templates/mainapp/blocks/random_prod.html
<div class="col-md-12">
    <div class="row">
        <div class="products-tabs">
            <!-- tab -->
            <div id="tab2" class="tab-pane fade in active">
                <div class="products-slick" data-nav="#slick-nav-2">
                    {% for p in prods %}
                        <div class="product">
                            <div class="product-img">
                                <img src="/media/{{ p.main_image }}" alt="">
                                <div class="product-label">
                                    {% if p.discount == True %}
                                        <div class="product-label">
                                            <span class="sale">-{{ p.size_discount }}%</span>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="product-body">
                                <p class="product-category">{{ p.category }}</p>
                                <h3 class="product-name"><a href="#">{{ p.name_model }}</a></h3>
                                <h4 class="product-price">{{ p.price }}Р
                                    <del class="product-old-price">0</del>
                                </h4>
                            </div>
                            <div class="add-to-cart">
                                <a href="{% url 'detail_prod' p.url%}" class="primary-btn">
                                    Перейти к деталям
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!-- /tab -->
        </div>
    </div>
</div>