cartapp/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove

app_name = "cartapp"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<url>", cart_add, name="cart_add"),
    path("remove/<url>", cart_remove, name="cart_remove"),
]

onlineshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainapp.urls")),
    path("", include("detailsapp.urls")),
    path("", include("filterprodapp.urls")),
    path("", include("sendemail.urls")),
    path("cart/", include("cartapp.urls", namespace="cart")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordersapp/urls.py
from django.urls import path
from .views import order_create

app_name = "ordersapp"

urlpatterns = [
    path("create/", order_create, name="order_create"),
]

cartapp/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        widget=forms.Select(
            attrs={
                "class": "input-select",
            }
        ),
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mainapp.models import Products
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, url):
    cart = Cart(request)
    product = get_object_or_404(Products, url=url)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd["quantity"], update_quantity=cd["update"])
    return redirect("cart:cart_detail")


def cart_remove(request, url):
    cart = Cart(request)
    product = get_object_or_404(Products, url=url)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    return render(request, "cartapp/detail.html", {"cart": cart})

cartapp/templates/cartapp/detail.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block content %}
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12 order-details">
                    <div>
                        <a href="{% url "filter_prod" %}" class="button light"><i class="fa fa-arrow-circle-left"
                                                                                  aria-hidden="true"></i> Продолжить
                            покупки</a>
                    </div>
                    <div class="section-title text-center">
                        <h3 class="title">Ваш Заказ</h3>
                    </div>
                    <div class="order-summary">
                        <div class="order-col">
                            <div><strong>Товар</strong></div>
                            <div><strong>Всего</strong></div>
                        </div>
                        <div class="order-products">
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <div class="order-col">
                                        <div>
                                            <form action="{% url "cart:cart_remove" product.url %}" method="post">
                                                {{ cart_product_form }}
                                                {% csrf_token %}
                                                <button class="delete" type="submit" value="Remove to cart" style="  background: #1e1f29; border: none; color: #FFF;"><i
                                                        class="fa fa-close"></i></button>
                                            </form>
                                        </div>
                                        <div style="position: relative; right: 65px;"><h4>{{ item.quantity }}x {{ product.brand }} {{ product.name_model }}</h4></div>
                                        <div><h4>{{ item.total_price }}Р.</h4></div>
                                    </div>
                                {% endwith %}
                            {% endfor %}
                        </div>
                        <div class="order-col">
                            <div><strong>Всего</strong></div>
                            <div><strong class="order-total">{{ cart.get_total_price }}Р.</strong></div>
                        </div>
                    </div>
                    <div class="payment-method">
                        <div class="input-radio">
                            <input type="radio" name="payment" id="payment-1">
                            <label for="payment-1">
                                <span></span>
                                Оплата картой
                            </label>
                            <div class="caption">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua.</p>
                            </div>
                        </div>
                        <div class="input-radio">
                            <input type="radio" name="payment" id="payment-2">
                            <label for="payment-2">
                                <span></span>
                                Оплата при получении
                            </label>
                            <div class="caption">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua.</p>
                            </div>
                        </div>
                        <div class="input-radio">
                            <input type="radio" name="payment" id="payment-3">
                            <label for="payment-3">
                                <span></span>
                                Оплата Paypal
                            </label>
                            <div class="caption">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua.</p>
                            </div>
                        </div>
                    </div>
                    <div class="input-checkbox">
                        <input type="checkbox" id="terms">
                        <label for="terms">
                            <span></span>
                            Я прочитал(а) все <a href="#">условия & предложения</a>
                        </label>
                    </div>
                    <a href="{% url "ordersapp:order_create" %}" class="primary-btn cta-btn">Оформить заказ</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}