cartapp/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove

app_name = "cartapp"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<url>", cart_add, name="cart_add"),
    path("remove/<url>", cart_remove, name="cart_remove"),
]

mainapp/urls.py
from django.urls import path
from .views import MainView, contact, about

urlpatterns = [
    path("", MainView.as_view(), name="main"),
    path("contacts/", contact, name="contacts"),
    path("about/", about, name="about"),
]

onlineshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainapp.urls")),
    path("", include("detailsapp.urls")),
    path("", include("filterprodapp.urls")),
    path("", include("sendemail.urls")),
    path("cart/", include("cartapp.urls", namespace="cart")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Categories(models.Model):
    name = models.CharField(
        "Название категории",
        max_length=25,
        db_index=True,
    )
    image = models.ImageField("Изображение", upload_to="image/catigories/%Y/%m/%d")
    url = models.SlugField(
        max_length=52,
        db_index=True,
        blank=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def save(
        self,
        *args,
    ):
        if not self.id:
            self.url = slugify(self.name)
        super(Categories, self).save(*args)

    def get_absolute_url(self):
        return reverse("scat", kwargs={"cat_slug": self.url})

    def __str__(self):
        return f"{self.name}"


class Brands(models.Model):
    name = models.CharField("Бренд", max_length=40, db_index=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Products(models.Model):
    name_model = models.CharField("Название", max_length=100, db_index=True)
    discription = models.TextField("Описание", max_length=1000, db_index=True)
    price = models.IntegerField(
        "Цена",
    )
    size_discount = models.IntegerField("Скидка", default=0)
    main_image = models.ImageField(
        "Главное изображение",
        upload_to="image/products/%Y/%m/%d",
    )
    category = models.ForeignKey(
        Categories,
        on_delete=models.CASCADE,
    )
    brand = models.ForeignKey(
        Brands,
        on_delete=models.CASCADE,
    )
    discount = models.BooleanField(default=False)
    available = models.BooleanField(default=True)
    url = models.SlugField(max_length=52, db_index=True, blank=True)

    class Meta:
        ordering = ["category"]
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def price_with_disk(self):
        return self.price - round(self.price * (self.size_discount / 100))

    def save(
        self,
        *args,
    ):
        if not self.id:
            self.url = slugify(self.name_model)
        super(Products, self).save(*args)

    def __str__(self):
        return f"{self.name_model}"


class Image(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    image = models.ImageField("Изображение", upload_to=f"image/products/%Y/%m/%d")

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"

    def __str__(self):
        return f"{self.product}"

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View

from cartapp.cart import Cart
from cartapp.forms import CartAddProductForm
from .models import Categories, Products


class MainView(View):
    def get(self, request, *args, **kwargs):
        prod = Products.objects.order_by("?")[:6]
        categories = Categories.objects.order_by("?")[:3]
        context = {
            "prods": prod,
            "cat": categories,
        }
        return render(request, "mainapp/main.html", context=context)


def cart_detail(request):
    cart = Cart(request)
    cart_form = CartAddProductForm()
    return render(
        request,
        "mainapp/blocks/header.html",
        {"cart": cart, "cart_product_form": cart_form},
    )


def contact(request):
    return render(request, "mainapp/plug.html", context={})


def about(request):
    return render(request, "mainapp/plug.html", context={})

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Electro - HTML Ecommerce Template</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static '/mainapp/css/bootstrap.min.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static '/mainapp/css/slick.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static '/mainapp/css/slick-theme.css' %}"/>
    <link type="text/css" rel="stylesheet" href="{% static '/mainapp/css/nouislider.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/mainapp/css/font-awesome.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static '/mainapp/css/style.css' %}">
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

</head>
<body>
<!-- HEADER -->
{% block header %}
    {% include './blocks/header.html' %}
{% endblock %}
<!-- /HEADER -->

<!-- CONTENT -->
{% block content %}
{% endblock %}
<!-- /CONTENT -->

{% if request.path != '/contact/' and request.path != '/success/' %}
    {% block application %}
        {% include './blocks/application.html' %}
    {% endblock %}
{% endif %}

<!-- FOOTER -->
{% block footer %}
    {% include './blocks/footer.html' %}
{% endblock %}
<!-- /FOOTER -->

<!-- jQuery Plugins -->
<script src="{% static 'mainapp/js/jquery.min.js' %}"></script>
<script src="{% static 'mainapp/js/bootstrap.min.js' %}"></script>
<script src="{% static 'mainapp/js/slick.min.js' %}"></script>
<script src="{% static 'mainapp/js/nouislider.min.js' %}"></script>
<script src="{% static 'mainapp/js/jquery.zoom.min.js' %}"></script>
<script src="{% static 'mainapp/js/main.js' %}"></script>
<script src="https://kit.fontawesome.com/7a33e924f9.js" crossorigin="anonymous"></script>
</body>
</html>

mainapp/templates/mainapp/detail_prod.html
{% extends 'mainapp/base.html' %}
{% load spurl %}
{% load static %}
{% load mathfilters %}
{% load my_filters %}


{% block content %}
    <div id="breadcrumb" class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb-tree">
                        <li><a href="{% url 'main' %}">Главная</a></li>
                        <li><a href="{% url 'filter_prod' %}">Товары</a></li>
                        <li class="active">{{ prod.brand }} {{ prod.name_model }}</li>
                    </ul>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- SECTION -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- Product main img -->
                <div class="col-md-5 col-md-push-2">
                    <div id="product-main-img">
                        {% for i in prod.image_set.all %}
                            <div class="product-preview">
                                <img src="/media/{{ i.image }}" alt="">
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- /Product main img -->

                <!-- Product thumb imgs -->
                <div class="col-md-2  col-md-pull-5">
                    <div id="product-imgs">
                        {% for i in prod.image_set.all %}
                            <div class="product-preview">
                                <img src="/media/{{ i.image }}" alt="">
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- /Product thumb imgs -->

                <!-- Product details -->
                <div class="col-md-5">
                    <div class="product-details">
                        <h2 class="product-name">{{ prod.brand }} {{ prod.name_model }}</h2>
                        <div>
                            <div class="product-rating">
                                {% if ar2 %}
                                    {% for s in ar2|range %}
                                        <i class="fa fa-star"></i>
                                    {% endfor %}
                                    {% for s in 5|sub:ar2|range %}
                                        <i class="fa fa-star-o"></i>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <a class="review-link" href="">{{ rp|length }} отзывов</a>
                        </div>
                        <div>
                            {% if prod.discount == True %}
                                <h3 class="product-price">{{ prod.price_with_disk }}₽
                                    <del class="product-old-price">{{ prod.price }}₽</del>
                                </h3>
                            {% else %}
                                <h3 class="product-price">{{ prod.price }}₽</h3>
                            {% endif %}
                            <span class="product-available">
                                {% if prod.available == True %}
                                    В наличии
                                {% else %}
                                    Нет в наличии
                                {% endif %}
                            </span>
                        </div>
                        <p>{{ prod.discription|truncatechars:10 }}</p>
                        <div class="product-options">
                            <label>
                                Память
                                <select class="input-select">
                                    <option value="64">64</option>
                                    <option value="128">128</option>
                                    <option value="256">256</option>
                                </select>
                            </label>
                            <label>
                                Цвет
                                <select class="input-select">
                                    <option value="red">Красный</option>
                                    <option value="black">Черный</option>
                                    <option value="white">Белый</option>
                                </select>
                            </label>
                        </div>

                        <div class="add-to-cart">
                            <div class="qty-label">
                                Кол-во
                                <div class="input-number">
                                    <input type="number">
                                    <span class="qty-up">+</span>
                                    <span class="qty-down">-</span>
                                </div>
                            </div>

                        </div>

                        <ul class="product-btns">
                            <li><a href="#"><i class="fa fa-heart-o"></i> Добавить в избранное</a></li>
                        </ul>

                        <ul class="product-links">
                            <li>Категория:</li>
                            <li><a href="#">{{ prod.category.name }}</a></li>
                        </ul>

                        <ul class="product-links">
                            <li>Поделиться:</li>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i></a></li>
                        </ul>

                    </div>
                </div>
                <!-- /Product details -->
                <form action="{% url "cart:cart_add" prod.url %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <button type="submit" value="Add to cart"> jepa</button>
                </form>
                <!-- Product tab -->
                <div class="col-md-12">
                    <div id="product-tab">
                        <!-- product tab nav -->
                        <ul class="tab-nav">
                            <li class="active"><a data-toggle="tab" href="#tab1">Описание</a></li>
                            <li><a data-toggle="tab" href="#tab2">Детали</a></li>
                            <li><a data-toggle="tab" href="#tab3">Отзывы ({{ rp|length }})</a></li>
                        </ul>
                        <!-- /product tab nav -->

                        <!-- product tab content -->
                        <div class="tab-content">
                            <!-- tab1  -->
                            <div id="tab1" class="tab-pane fade in active">
                                <div class="row">
                                    <div class="col-md-12">
                                        <p>{{ prod.discription }}</p>
                                    </div>
                                </div>
                            </div>
                            <!-- /tab1  -->

                            <!-- tab2  -->
                            <div id="tab2" class="tab-pane fade in">
                                <div class="row">
                                    <div class="col-md-12">
                                        <p></p>
                                    </div>
                                </div>
                            </div>
                            <!-- /tab2  -->

                            <!-- tab3  -->
                            {% block reviews %}
                                {% include '/home/vladimir/Djangoproject/onlineshop/onlineshop/reviewsapp/templates/reviewsapp/show_reviews.html' %}
                            {% endblock %}
                            <!-- /tab3  -->
                        </div>
                        <!-- /product tab content  -->
                    </div>
                </div>
                <!-- /product tab -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /SECTION -->

    <!-- Section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="section-title text-center">
                        <h3 class="title">Рекомендуемые товары</h3>
                    </div>
                </div>

                <!-- product -->

                {% include 'mainapp/blocks/random_prod.html' %}


                <!-- /product -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /Section -->
{% endblock %}

mainapp/templates/mainapp/main.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h3 class="title">Категории</h3>
                    </div>
                </div>
                <!-- shop -->
                {% for c in cat %}
                    <div class="col-md-4 col-xs-6">
                        <div class="shop">
                            <div class="shop-img">
                                <img src="media/{{ c.image }}" alt="">
                            </div>
                            <div class="shop-body">
                                <h3>{{ c.name }}</h3>
                                <a href="/products/?cat={{ c.name }}&price-min=1&price-max=999999&show=12"
                                   class="cta-btn">Купить сейчас <i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <!-- /shop -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>

    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <!-- section title -->
                <div class="col-md-12">
                    <div class="section-title">
                        <h3 class="title">Новое поступление</h3>
                    </div>
                </div>
                <!-- /section title -->

                <!-- Products tab & slick -->
                {% include 'mainapp/blocks/random_prod.html' %}
                <!-- Products tab & slick -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>

    <div id="hot-deal" class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="hot-deal">
                        <ul class="hot-deal-countdown">
                            <li>
                                <div>
                                    <h3>02</h3>
                                    <span>Дня</span>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <h3>10</h3>
                                    <span>Часов</span>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <h3>34</h3>
                                    <span>Минут</span>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <h3>60</h3>
                                    <span>Секунд</span>
                                </div>
                            </li>
                        </ul>
                        <h2 class="text-uppercase">Лучшее предложение недели</h2>
                        <p>Новое поступление до 50% скидка</p>
                        <a class="primary-btn cta-btn" href="/products/?disc=1&price-min=1&price-max=999999&show=12">Купить
                            сейчас</a>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>

    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <!-- section title -->
                <div class="col-md-12">
                    <div class="section-title">
                        <h3 class="title">Топ продаж на сегодня</h3>

                    </div>
                </div>
                <!-- /section title -->
                <!-- Products tab & slick -->
                {% include 'mainapp/blocks/random_prod.html' %}
                <!-- /Products tab & slick -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>

{% endblock %}

mainapp/templates/mainapp/plug.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
        <div class="container">
        <div class="row">
            <div class="successh2">
                <h1 style="text-align: center">Раздел находится в разработке.</h1>
            </div>
        </div>
    </div>
{% endblock %}